### ISSUE TITLE
Get an access token got error 

### ISSUE THREAD

**Issue by satya5561** [wapacro/Skype-for-Business-UCWA-PHP#3]
when i am trying to call 
`<?php
  require( "lib/base.ucwa.class.php" );
  $ucwa = new UCWA_init( "http://myapp.example.com" );
  $ucwa->getAccessToken( "some.user@yourdomain.com", "P@ssw0rd!" );
?>`

got error 
` {"error":"unsupported_grant_type"}`

**Comment by wapacro** [comment]
According to the [official documentation](https://ucwa.skype.com/documentation/GettingStarted-Authentication) the _unsupported_grant_type_ error is thrown if the specified grant type (in this case _password_) is not supported by the server. 

Are you using an On-Premise solution?

**Comment by wapacro** [comment]
Closed due to inactivity
